- name: install zabbix_agent2
  hosts: all
  serial: 4
  vars:
    - ZX_SERVER: "172.16.12.70"
    - ZX_VER: "7.0"
    - ZX_URL: "https://repo.zabbix.com/zabbix"
    - OS_Version: "9"
  tasks:
   - name: Redhat Istall repo
     block:
      - name: rocky repo
        shell: "rpm -Uvh https://repo.zabbix.com/zabbix/7.0/rhel/9/x86_64/zabbix-release-latest-7.0.el9.noarch.rpm"
        ignore_errors: yes
      - name: Redhat Istall zabbix-agent2
        yum:
          name: zabbix-agent2
          state: present
        when: ansible_distribution_file_variety == "RedHat"

   - name: config Server
     replace:
      path: /etc/zabbix/zabbix_agent2.conf
      regexp: "Server=127.0.0.1"
      replace: "Server={{ ZX_SERVER }}"
     notify:
      - restart agent2

   - name: service
     service:
      name: zabbix-agent2.service
      state: started
      enabled: yes

  handlers:
  - name: restart agent2
    service:
      name: zabbix-agent2.service
      state: restarted
